basic.forever(function () {
    led.plot(2, 3)
    basic.pause(100)
    basic.clearScreen()
    led.plot(2, 4)
    basic.pause(100)
    basic.clearScreen()
    led.plot(4, 4)
    basic.pause(100)
    led.plot(0, 0)
    basic.pause(100)
    basic.clearScreen()
    led.plot(0, 1)
    basic.pause(100)
    basic.clearScreen()
    led.plot(0, 2)
    basic.pause(100)
    basic.clearScreen()
    led.plot(1, 4)
    basic.pause(100)
    basic.clearScreen()
    led.plot(4, 0)
    basic.pause(100)
    basic.clearScreen()
    led.plot(1, 4)
    basic.pause(100)
    basic.clearScreen()
    led.plot(4, 2)
    basic.pause(100)
    basic.clearScreen()
    led.plot(3, 1)
})
